// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooBook.Infra.Data.Context;

namespace ZooBook.Infra.Data.Migrations
{
    [DbContext(typeof(ZooBookDbContext))]
    partial class ZooBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZooBook.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = "eae45a1b2684461f8ed1dd4fbee63743",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 177, DateTimeKind.Local).AddTicks(3041),
                            FirstName = "Md",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "AshfaQ",
                            MiddleName = "Badhon"
                        },
                        new
                        {
                            Id = "b00e553cfdd24091b207ed02dcb27374",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(950),
                            FirstName = "John",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Well",
                            MiddleName = "Max"
                        },
                        new
                        {
                            Id = "bc18004d54b34a819796de536a1d56f9",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(991),
                            FirstName = "Tom",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Goong",
                            MiddleName = "Tang"
                        },
                        new
                        {
                            Id = "e721b24fc73a4d82a4c881c75ed2d805",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(1001),
                            FirstName = "Tokio",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Oscer",
                            MiddleName = "Servei"
                        },
                        new
                        {
                            Id = "27d82f92026a4445ba3001c3da646336",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(1008),
                            FirstName = "Mark",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Allen",
                            MiddleName = "Tiger"
                        },
                        new
                        {
                            Id = "33e386fc66a74029a86261e475f2a2ea",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(1029),
                            FirstName = "Alen",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pirer",
                            MiddleName = "Max"
                        },
                        new
                        {
                            Id = "297e20b8e110485eb9bfe911b2ca687d",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(1057),
                            FirstName = "Rasell",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Barnerd",
                            MiddleName = "Shaw"
                        },
                        new
                        {
                            Id = "9c4f545d78344a9690db4f6f95812015",
                            CreateTime = new DateTime(2021, 5, 27, 15, 40, 45, 179, DateTimeKind.Local).AddTicks(1064),
                            FirstName = "Envy",
                            IsDeleted = false,
                            LastModifiedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "John",
                            MiddleName = "Goodwill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
